=== jorotenev/para/app/para-common/expense_json_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "ExpenseObject",
    "description": "timetmap regex from https://www.myintervals.com/blog/2009/05/20/iso-8601-date-validation-that-doesnt-suck/ and modified to require tz",
    "type": "object",
    "definitions": {
        "timestamp": {
            "type": "string",
            "description":"2017-10-29T09:09:21.853071Z and not 2017-10-29T09:09:21.853071+00:00",
            "pattern": "^([\\+-]?\\d{4}(?!\\d{2}\\b))((-?)((0[1-9]|1[0-2])(\\3([12]\\d|0[1-9]|3[01]))|W([0-4]\\d|5[0-2])(-?[1-7])|(00[1-9]|0[1-9]\\d|[12]\\d{2}|3([0-5]\\d|6[1-6])))([T\\s]((([01]\\d|2[0-3])((:?)[0-5]\\d)|24\\:?00)([\\.,]\\d+(?!:))?)(\\17[0-5]\\d([\\.,]\\d+))([Z])))$"
        }
    },
    "properties": {
        "id": {"type": ["string", "null"]},
        "name": {"type": "string"},
        "amount": {"type": "number"},
        "tags": {"type": "array", "maxItems":10, "uniqueItems":true, "items": {"type": "string"}},
        "currency": {"type": "string", "pattern": "^[A-Z]{3}$"},
        "timestamp_utc": {
            "$ref": "#/definitions/timestamp"
        },
        "timestamp_utc_created": {
            "$ref": "#/definitions/timestamp"
        },
        "timestamp_utc_updated": {
            "$ref": "#/definitions/timestamp"
        }
    },
    "required": ["id", "name", "amount", "tags", "currency", "timestamp_utc", "timestamp_utc_created", "timestamp_utc_updated"],
    "additionalProperties":false
}

=== jorotenev/para/app/para-common/sample_expenses.json
[
  {
    "id": "0d252a9e-4cb4-4da1-b483-8d2d0c0753b4",
    "name": "server id 1",
    "amount": 12.5,
    "currency": "EUR",
    "tags": [
      "work",
      "sport"
    ],
    "timestamp_utc": "2017-10-29T09:09:21.853071Z",
    "timestamp_utc_created": "2017-10-29T09:09:21.853071Z",
    "timestamp_utc_updated": "2017-10-29T09:09:21.853071Z"
  },
  {
    "id": "fa8b1e8c-dfbd-4123-98fb-c0a4823ee520",
    "name": "server id 2",
    "amount": 118.1,
    "currency": "EUR",
    "tags": [
      "vacation"
    ],
    "timestamp_utc": "2017-10-29T09:10:21.853071Z",
    "timestamp_utc_created": "2017-10-29T09:10:21.853071Z",
    "timestamp_utc_updated": "2017-10-29T09:10:21.853071Z"
  },
  {
    "id": "db29ed23-a7ee-4448-96cd-ab37c7e83f57",
    "name": "server id 3",
    "amount": 159.1,
    "currency": "EUR",
    "tags": [
      "vacation",
      "work",
      "home"
    ],
    "timestamp_utc": "2017-10-29T09:11:21.853071Z",
    "timestamp_utc_created": "2017-10-29T09:11:21.853071Z",
    "timestamp_utc_updated": "2017-10-29T09:11:21.853071Z"
  },
  {
    "id": "1f3cb03e-f8e1-4d5c-bbde-a9ef3ea455f8",
    "name": "server id 4",
    "amount": 5.1,
    "currency": "EUR",
    "tags": [
      "sport",
      "vacation"
    ],
    "timestamp_utc": "2017-10-29T09:12:21.853071Z",
    "timestamp_utc_created": "2017-10-29T09:12:21.853071Z",
    "timestamp_utc_updated": "2017-10-29T09:12:21.853071Z"
  },
  {
    "id": "f97fa2ab-66be-40bd-bf7e-f1fd5eae8401",
    "name": "server id 5",
    "amount": 184.1,
    "currency": "EUR",
    "tags": [
      "sport",
      "home",
      "vacation"
    ],
    "timestamp_utc": "2017-10-29T09:13:21.853071Z",
    "timestamp_utc_created": "2017-10-29T09:13:21.853071Z",
    "timestamp_utc_updated": "2017-10-29T09:13:21.853071Z"
  },
  {
    "id": "bd793e01-cae9-4ff8-a0fe-94acd8efcbf7",
    "name": "server id 6",
    "amount": 191.1,
    "currency": "EUR",
    "tags": [
      "work"
    ],
    "timestamp_utc": "2017-10-29T09:14:21.853071Z",
    "timestamp_utc_created": "2017-10-29T09:14:21.853071Z",
    "timestamp_utc_updated": "2017-10-29T09:14:21.853071Z"
  },
  {
    "id": "dff1e980-8f21-4450-a334-fa26eb6c4bd5",
    "name": "server id 7",
    "amount": 134.1,
    "currency": "EUR",
    "tags": [
      "vacation",
      "home"
    ],
    "timestamp_utc": "2017-10-29T09:15:21.853071Z",
    "timestamp_utc_created": "2017-10-29T09:15:21.853071Z",
    "timestamp_utc_updated": "2017-10-29T09:15:21.853071Z"
  },
  {
    "id": "d7df5e82-c05f-426e-99b1-2153f65cf802",
    "name": "server id 8",
    "amount": 132.1,
    "currency": "EUR",
    "tags": [],
    "timestamp_utc": "2017-10-29T09:16:21.853071Z",
    "timestamp_utc_created": "2017-10-29T09:16:21.853071Z",
    "timestamp_utc_updated": "2017-10-29T09:16:21.853071Z"
  },
  {
    "id": "402cb195-a033-4891-8a69-b8d6e7201067",
    "name": "server id 9",
    "amount": 71.1,
    "currency": "EUR",
    "tags": [
      "vacation"
    ],
    "timestamp_utc": "2017-10-29T09:17:21.853071Z",
    "timestamp_utc_created": "2017-10-29T09:17:21.853071Z",
    "timestamp_utc_updated": "2017-10-29T09:17:21.853071Z"
  },
  {
    "id": "5501735d-99ac-41b9-9c23-1d612d22dc2a",
    "name": "server id 10",
    "amount": 95.1,
    "currency": "EUR",
    "tags": [
      "vacation",
      "work"
    ],
    "timestamp_utc": "2017-10-29T09:18:21.853071Z",
    "timestamp_utc_created": "2017-10-29T09:18:21.853071Z",
    "timestamp_utc_updated": "2017-10-29T09:18:21.853071Z"
  }
]
